name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Npm install
        run: |
          npm install
          npm run pretest
      - name: Run TestCafe E2E Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "--page-load-timeout 60000 --selector-timeout 30000 'chrome:headless --no-sandbox --disable-dev-shm-usage' tests"
