name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run pretest
        run: npm run pretest
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"
